name: kyrgyz_tourism
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  # Navigation
  auto_route: ^10.0.1

  # network
  dio: ^5.8.0+1

  # di
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  injectable: ^2.5.0
  flutter_bloc: ^9.1.0
  logger: ^2.5.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  firebase_auth: ^5.5.3
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: null

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  json_serializable: ^6.9.4
  retrofit_generator: '>=8.0.0 <10.0.0'
  injectable_generator: ^2.7.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  background_image: assets/splash_background.png
  # color: "#fb87ff"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:

    - assets/images/
    - assets/icon/
    - assets/api/
flutter_intl:
  enabled: true
